### ISSUE TITLE
libremesh/encrypt-11s selects wpad-mesh but does not deselect wpad-mini

### ISSUE THREAD

**Issue by ilario** [libremesh/network-profiles#13]
Using the `libremesh/encrypt-11s` network profile selects the `wpad-mesh` package but also the `wpad-mini` package is installed even if useless in this case.
Refer to the discussion on libremesh/chef#8

**Comment by digitigrafo** [comment]
And also the command are not rights in this file:

https://github.com/libremesh/network-profiles/blob/master/libremesh/encrypt-11s/etc/uci-defaults/80-set-11s-encryption

These work:

    uci set lime-defaults.wifi.ieee80211s_encryption='psk2+aes'

    uci set lime-defaults.wifi.ieee80211s_key='libremesh'

    uci commit lime-defaults  

    lime-config

**Comment by digitigrafo** [comment]
About the 2 pckage you can remove wpad-mini and install wpad-mesh after flashing
https://wiki.bologna.ninux.org/mediawiki/index.php/Layer_encryption_su_libremesh

**Comment by G10h4ck** [comment]
As soon as something is doable at compile time instead of at run-time it is better to do it at compile time, in particular if the right package is in place at compile time it will need less space on device because of squashfs compression.

About the way the encryption is enabled in configuration I am not sure if putting an uci-default script is the most elegant way... but i am not expert w.r.t. lime-sdk

In any case if you have experienced your commands works and the one in the current distribution does not i invite you to prepare a merge request and we will be happy to accept it :)

Cheers!

**Comment by p4u** [comment]
First of all, these profiles are just examples, please read the README file attached to the libremesh network profile

https://github.com/libremesh/network-profiles/tree/master/libremesh

@G10h4ck it is done using a uci-defaults script cause this way it can be easily imported to another profile. Adding the changes directly to /etc/config/lime-defaults would override an existing lime-defaults file. In addition this way does not break the default settings in case there is some new option added to lime-defaults (or some important change). So it's less intrusive IMO. If someone else has a better solution, let's discuss it.

@digitigrafo I fixed the missing "uci commit", thanks for reporting.

@ilario remove wpad-mini is easy, just add -wpad-mini to the PACKGES file should work. I was not 100% sure if wpad-mini was required or not, but if it is tested (wpad-mesh replaces completelly wpad-mini) then I'll add the removal.

https://github.com/libremesh/network-profiles/blob/master/libremesh/encrypt-11s/PACKAGES

**Comment by FreifunkUFO** [comment]
see also this ticket https://github.com/libremesh/chef/issues/8
was the problem solved meanwhile?

**Comment by p4u** [comment]
@FreifunkUFO create the profile and use the PACKAGES file to make your own selection/deselection of packages. Have you tried it? This should fix your problem.

**Comment by FreifunkUFO** [comment]
@p4u @aparcar isnt it already existing?
i just tried chef.libremesh.org with profile libremesh-11s-encrypted... and still wpad-mini AND wpad-mesh will be installed:
https://ledeupdate.planetexpress.cc/json/lime/17.06/ar71xx/generic/tl-wdr3600-v1/ce9a9c4c302992a/build-f60efb1cea96c00.log

**Comment by aparcar** [comment]
@FreifunkUFO I think currently there is no solution for adding packages but removing others. Is it possible to create "negative" dependencies?
You could create a PR for a flavor with wpad-mesh instead of mini as well.

@dangowrt do you have thoughts on that issue?

**Comment by FreifunkUFO** [comment]
@aparcar see https://github.com/libremesh/network-profiles/commit/5ab8abfc32f09b7f3ebfa81db2a1d01bc5b95c29

**Comment by p4u** [comment]
I just tested and it works for me using cooker.

```
lime@compile:~/lime-sdk$ ./cooker -c ar71xx/generic --profile=tl-wdr4300-v1 --community=libremesh/encrypt-11s

-> Using community files from /home/lime/lime-sdk/communities/libremesh/encrypt-11s
-> Cooking ar71xx/generic/tl-wdr4300-v1
--> Adding community packages: 
--> Copying community files
-> Cooking firmware image
--> Selected extra packages: wpad-mesh -wpad-mini lime-full -dnsmasq

make: Entering directory '/home/lime/lime-sdk/17.01.4/ar71xx/generic/ib'
make[1]: Entering directory '/home/lime/lime-sdk/17.01.4/ar71xx/generic/ib'
echo 'Building images for ar71xx - TP-LINK TL-WDR4300 v1'
Building images for ar71xx - TP-LINK TL-WDR4300 v1
echo 'Packages: wpad-mesh lime-full base-files busybox dropbear firewall fstools ip6tables iptables kernel kmod-ath9k kmod-gpio-button-hotplug kmod-usb-core kmod-usb-ledtrig-usbport kmod-usb2 libc libgcc logd mtd netifd odhcp6c odhcpd opkg ppp ppp-mod-pppoe swconfig uboot-envtools uci uclient-fetch'
Packages: wpad-mesh lime-full base-files busybox dropbear firewall fstools ip6tables iptables kernel kmod-ath9k kmod-gpio-button-hotplug kmod-usb-core kmod-usb-ledtrig-usbport kmod-usb2 libc libgcc logd mtd netifd odhcp6c odhcpd opkg ppp ppp-mod-pppoe swconfig uboot-envtools uci uclient-fetch

```
@aparcar the same could be implemented on chef. But instead of just using the OPKG profile packages, you must also have access to the special file PACKAGES of the network-profile. Then add the contents of it to the "PACKAGES=" variable of LEDE ImageBuilder.

**Comment by ilario** [comment]
Works also for me, closing.
