### ISSUE TITLE
Permission Request

### ISSUE THREAD

**Issue by 2Vera** [libremesh/network-profiles#26]
Hello!

I don't want to be in the Libremesh mailing list but I do need permission to edit the EspaiVeinal network profile while I'm helping @amuuza, so can I ask for it through this issue? 

Thanks!

**Comment by G10h4ck** [comment]
You can fork the repository, edit on the fork and then do pull requests to have it modified on main repo

**Comment by nicopace** [comment]
Based on how it is being done till now, I granted permission to you @2Vera .
Tough, we need to revise this policy to see what fits best, right @G10h4ck ?
