### ISSUE TITLE
Config stays empty, wifi networks not coming up after flashing

### ISSUE THREAD

**Issue by ghost** [libremesh/network-profiles#35]
Hello :)

I am experiencing some weird behavior, that causes my builds to be broken in some way, that it is missing the actual configuration from the community profile in the **wireless** config file.
I was trying different things including modifying profiles and creating my own community profile.

Here is a full build and flash log: https://gist.github.com/janphilippi/738785a43eca9176590ea250f6b55b21

Here is the output of **uci show** right after the flash process and reboot: https://gist.github.com/janphilippi/20b0ce484dc4a7334679eecdb8fb1ff0

The config files are pretty empty (specially **/etc/config/wireless**): https://gist.github.com/janphilippi/574e0f023e469df38c835596cb29b6e8

Expected result:
Wireless networks configured and starting on boot.

Actual result:
Config file is empty and wireless networks are not starting on boot.

**Comment by nicopace** [comment]
In LibreMesh, instead of using /etc/config/wireless, you need to use the simplified config /etc/config/lime
https://libremesh.org/docs/en_config.html
The /etc/config/wireless file is overwritten at first boot (and every time you run lime-config), so any config you might be doing there will be overwrote.

**Comment by ilario** [comment]
I agree with @nicopace, the community network-profile should include an `/etc/config/lime-defaults` file with the settings.
For having some examples you can have a look at [other communities network-profiles](https://github.com/libremesh/network-profiles) or at lime-example (on `/docs/lime-example` or [here](https://github.com/libremesh/lime-packages/blob/master/packages/lime-docs/files/lime-example))

**Comment by ghost** [comment]
This doc (https://github.com/libremesh/lime-packages/blob/master/packages/lime-docs/files/lime-example) is actually pure gold.

Thank you for sharing this one.
