### ISSUE TITLE
Encrypted mesh knocks AP offline

### ISSUE THREAD

**Issue by tomjones1977** [libremesh/network-profiles#39]
When setting 

```
option ieee80211s_encryption 'psk2+aes' 
option ieee80211s_key 'someotherpassword'
```

the AP drops.  I can still access the node through the LAN, just not by WiFi.  

Node is an Ubiquiti Nanosation M5, firmware was created by chef:

Distributions: LibreMesh
Release: 17.06
Model: Ubiquiti Nano M XW
Target: ar71xx
Subtarget: generic

**/etc/config/lime:**

```
config lime 'system'
        option hostname 'LiMe-%M4%M5%M6'
        option domain 'lan'

config lime 'network'
        list protocols 'ieee80211s'
        list protocols 'lan'
        list protocols 'anygw'
        list protocols 'batadv:%N1'
        list protocols 'bmx6:13'
        list protocols 'olsr:14'
        list protocols 'olsr6:15'
        list protocols 'olsr2:16'
        list protocols 'babeld:17'
        option primary_interface 'eth0'
        list resolvers '4.2.2.2'
        list resolvers '141.1.1.1'
        list resolvers '2001:470:20::2'
        option main_ipv4_address '10.%N1.0.0/16'
        option main_ipv6_address '2a00:1508:0a%N1:%N200::/64'
        option anygw_mac 'aa:aa:aa:%N1:%N2:aa'
        option anygw_dhcp_start '2'
        option anygw_dhcp_limit '0'
        option bmx6_pref_gw 'none'
        option bmx6_over_batman 'false'
        option bmx6_mtu '1500'

config lime 'wifi'
        list modes 'ap'
        list modes 'apname'
        list modes 'ieee80211s'
        option apname_ssid 'LibreMesh.org/%H'
        option ap_ssid 'LibreMesh.org'
        option ieee80211s_mesh_id 'LiMe'
        option channel_2ghz '11'
        option adhoc_ssid 'LiMe'
        option adhoc_mcast_rate_5ghz '6000'
        option distance '1000'
        option htmode_5ghz 'HT40'
        option ieee80211s_mesh_fwding '0'
        option adhoc_mcast_rate_2ghz '24000'
        option channel_5ghz '48'
        option adhoc_bssid 'ca:fe:00:c0:ff:ee'
        option ieee80211s_encryption 'psk2+aes' 
        option ieee80211s_key 'someotherpassword'

config net 'lm_hwd_openwrt_wan'
        option autogenerated 'true'
        list protocols 'ieee80211s'
        list protocols 'anygw'
        list protocols 'batadv:%N1'
        list protocols 'bmx6:0'
        list protocols 'olsr:14'
        list protocols 'olsr6:15'
        list protocols 'olsr2:16'
        list protocols 'babeld:17'
        list protocols 'wan'
        option linux_name 'eth0.2'


```

**Comment by aparcar** [comment]
I remeber that some fixes for that were merged afterwards on openwrt 18.06. I'll try to offer a testing version of libremesh based on 18.06 and you could try again

**Comment by ilario** [comment]
Which network-profile are you using?
I'm asking because with the default network-profile the `wpad-mini` package is installed, but you will need to replace it with the more complete `wpad-mesh` that allows for ieee802.11s encryption (it would be interesting to know how much the image size increases and to consider if to include it by default) as documented [here](https://github.com/libremesh/lime-packages/blob/master/packages/lime-docs/files/lime-example#L74).

**Comment by tomjones1977** [comment]
I've tried rebuilding the firmware with wpad-mesh and confirmed it is installed on the nodes.  However I still have the same issues trying to establish an encrypted mesh.  

I have even tried removing the AP mode and just having it as a mesh only but this does not work either.

**Comment by dangowrt** [comment]
@tomjones1977 Which hardware are you targetting and which OpenWrt release or commit are you basing your build on?

**Comment by tomjones1977** [comment]
I'm using chef to build the images:

Distributions: LibreMesh
Release: 17.06
Model: Ubiquiti Rocket M XW
Target: ar71xx
Subtarget: generic

I'm using the Ubiquiti Rocket M5 XW, and Ubiquiti NanoStation M5 XW.

**Comment by dangowrt** [comment]
Please try the master branch of lime-sdk https://github.com/libremesh/lime-sdk/tree/master and use OpenWrt snapshot in chef, ie.
```
diff --git a/options.conf b/options.conf
index f4583c2..6fbaca1 100644
--- a/options.conf
+++ b/options.conf
@@ -1,9 +1,9 @@
 # check if SDK or IB is outdated before further actions
 snapshots=1
 # name of used release - just for storing IB and SDK
-release=18.06.1
+release=snapshots
 # where do download the SDK and ImageBuilder (IB) from
-base_url=https://downloads.openwrt.org/releases/$release/targets/
+base_url=https://downloads.openwrt.org/snapshots/targets/
 # git repository for network profiles
 communities_git=https://github.com/libremesh/network-profiles.git
 # local folder with network profiles aka community settings
```

**Comment by tomjones1977** [comment]
I was using chef online but I'll pull the SDK down and give it a try.

**Comment by tomjones1977** [comment]
I might be missing something obvious here but I can't see how to get cooker to use the snapshot instead of the 18.06 release?


`./cooker -c ar71xx/generic --profile=ubnt-rocket-m-xw --flavor=lime_default 
`

**Comment by ilario** [comment]
Can't you just use the stable 17.06 LibreMesh release based on LEDE for testing purposes?
For compiling the stable release just use the master branch of lime-sdk :)
Then you can include wpad-mesh with the --extra-pkg= option.
I don't know if that option can also be used for deselecting wpad-mini... @p4u

**Comment by tomjones1977** [comment]
> Can't you just use the stable 17.06 LibreMesh release based on LEDE for testing purposes?
> For compiling the stable release just use the master branch of lime-sdk :)
> Then you can include wpad-mesh with the --extra-pkg= option.
> I don't know if that option can also be used for deselecting wpad-mini... @p4u

I was only trying to get the later version as one of the previous comments mentioned 18.06 has some fixes related to the encrypted mesh option.  If I can get it working with a stable version I'd be a lot happier!

**Comment by tomjones1977** [comment]
So for anyone who gets here via google:

18.06.1 on the Chef development version online (as of 23/11/18) works correctly with wpad-mesh.  However it does have interface issues in terms of formatting but the networking seems to work okay.

**Comment by nordurljosahvida** [comment]
As we're speaking about this on 18.06 and I've just had the same issue, can anyone confirm or deny that hostapd and authsae [which I've always used pre-18.06] are *not* needed on 18.06? They're both causing errors on my builds done on the `develop` branch. However my 18.06 nodes are not meshing. Thanks in advance.

EDIT: They do actually mesh, but I'd still like to make sure they are not needed.

**Comment by dangowrt** [comment]
authsae is deprecated in favour of SAE support in hostapd/wpa_supplicant. just install wpad-mesh-openssl and encrypted mesh, including mesh+AP should work.

**Comment by nordurljosahvida** [comment]
Thank you. Can you confirm all of what you said is included in the package wpad? In my packages I have "-wpad-mini wpad". Thanks

**Comment by dangowrt** [comment]
No. wpad is the pre-mesh 'full' variant of wpa_suppilcant+hostapd which includes WPA-EAP and 802.1x features. Please use wpad-mesh instead, which includes everything in wpad plus support for 802.11s interfaces and SAE crypto, but needs an external crypto library because not all primitives needed for SAE have been implemented internally in hostapd/wpa_supplicant. Up to 18.06, wpad-mesh depends on openssl. Shortly after the 18.06 release of OpenWrt, support for using either openssl or wolfssl was added and more package variants (wpad-mesh-wolfssl, wpad-mesh-openssl, ...) introduced.

**Comment by nordurljosahvida** [comment]
Perfect thanks, so I should remove wpad, hostapd, authsae, and replace all of them with wpad-mesh and nothing else right?

Thanks again!

**Comment by dangowrt** [comment]
Exactly. wpad is basically just a single executable cotaining both, hostapd and wpa_supplicant. wpad-mesh additionally contains the functionality of authsea.

**Comment by nordurljosahvida** [comment]
Thank you so much. This is the list of packages I've committed on our [PACKAGES file](https://github.com/libremesh/network-profiles/blob/master/openNET.io/1144-W2PA-LIME-XXXX/PACKAGES):

```
lime-full
luci-ssl
wpad-mesh
ath10k-firmware-qca988x
kmod-ath10k
-wpad-mini
```
