### ISSUE TITLE
Update the Github Actions continuous integration to upload on lime-feed repository

### ISSUE THREAD

**Issue by ilario** [libremesh/network-profiles#68]
The Github Actions on this repository [currently fail](https://github.com/libremesh/network-profiles/runs/1226990132).
This is because it still uses @aparcar server instead than the [lime-feed repository](https://github.com/libremesh/lime-feed).
What has to be edited is:
https://github.com/libremesh/network-profiles/blob/f3839f5e1a0c66d94a22fc2e68bf993fe2f3f809/.github/workflows/build.yml#L31-L41
to became similar to:
https://github.com/libremesh/lime-packages/blob/f06b3dfb5b909bd96ce099ca8b660e48be0334e8/.github/workflows/build.yml#L33-L39
as implemented in https://github.com/libremesh/lime-packages/commit/f06b3dfb5b909bd96ce099ca8b660e48be0334e8

**Comment by aparcar** [comment]
I removed it
