### ISSUE TITLE
make router profile aware

### ISSUE THREAD

**Issue by aparcar** [libremesh/network-profiles#8]
in addition to #7 it could be useful to make the routers aware of the used network-profile so it can ask a possible [update server](https://blog.freifunk.net/2017/05/30/gsoc-2017-attended-sysupgrade/) to include the profile. 

Is this already implemented and I'm missing something?

**Comment by nicopace** [comment]
I think it is not implemneted... but it is actually a good idea to embed something like a 'fingerprint' of the config so it can be identified.
I think @p4u has been looking on this... (do you see a pattern here? ... :) ).

**Comment by aparcar** [comment]
May a possible solution:
* Generate the packages mentioned in #7 so a `opkg list` would already supply the information
or
* Add a simple txt/yaml file `/etc/network-profile` containing the network-profile name
  * Auto created via cooker/update-server
  * Put in the repository, may filled with additional information about the profile

**Comment by aparcar** [comment]
updates on this? It's not a must feature as config files should be saved on sysupgrade anyway

**Comment by nicopace** [comment]
Maybe this is something you need to ask for in the lime-sdk project

**Comment by aparcar** [comment]
Not only lime-sdk but the imagebuilder as well can "handle" network profiles...

**Comment by aparcar** [comment]
Solution would be to use the packages produced here:
https://github.com/libremesh/network-profiles/issues/7

**Comment by p4u** [comment]
I would include this information (network profile) to /etc/lime_release

The packages generated with your script might include, by default, an uci-defaults script to add an extra line to this file containing the network-profile information on first boot

Also lime-sdk (cooker) might be modified to write this uci-defaults scripts in case a --community is specified

**Comment by aparcar** [comment]
@p4u if installed via package the network-profile is withn the packagelist and would be automatically requested on sysupgrade. That solves the issue already for me.

Introducing a new parameter to lime_release makes it less "conform" with regular LEDE, in future I'd like to see all lime-packages move to official LEDE packages so not introduce to many special modifications.

_unify all the stuff!_

**Comment by aparcar** [comment]
All solved I think via this http://repo.libremesh.org/network-profiles/
